### ISSUE TITLE
STT inside alertDialog getting error

### ISSUE THREAD

**Issue by cosmosdesigner** [csdcorp/speech_to_text#157]
I have STT inside a alertDialog, and when a close and open again, and start listening without getting any word, getting this error:
`E/flutter (14349): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: setState() called after dispose(): _SpeetchToTextState#14854(lifecycle state: defunct, not mounted)
E/flutter (14349): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (14349): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (14349): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (14349): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1208:9)
E/flutter (14349): #1      State.setState (package:flutter/src/widgets/framework.dart:1243:6)
E/flutter (14349): #2      _SpeetchToTextState.errorListener (package:Intervenant/widgets/shared.dart:292:5)
E/flutter (14349): #3      SpeechToText._onNotifyError (package:speech_to_text/speech_to_text.dart:461:20)
E/flutter (14349): #4      MethodChannelSpeechToText._handleCallbacks (package:speech_to_text_platform_interface/method_channel_speech_to_text.dart:131:18)
E/flutter (14349): #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:430:55)
E/flutter (14349): #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:383:34)
E/flutter (14349): #7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283:33)
E/flutter (14349): #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
E/flutter (14349): #9      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (14349): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (14349): #11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (14349): #12     _invoke3 (dart:ui/hooks.dart:279:10)
E/flutter (14349): #13     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)`

When a do navigator.pop he dispose all, but i dont know if STT is disposed.

Please help.

**Comment by cosmosdesigner** [comment]
[ RESOLVED ], apparently all setStates are no disposabled, so there are some memory leak when you do a new instance.
I resolved using `if (mounted){setState((){})}` in all setState.

Thx and keep up the good work
