### ISSUE TITLE
App crashed Samsung note 20 bixby voice input

### ISSUE THREAD

**Issue by altanod0627** [csdcorp/speech_to_text#273]
Anyone fix this issue? 

java.lang.SecurityException: Not allowed to bind to service Intent { act=android.speech.RecognitionService cmp=com.samsung.android.bixby.agent/.mainui.voiceinteraction.MainVoiceInteractionService }
 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1918)
 	at android.app.ContextImpl.bindService(ContextImpl.java:1829)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:774)
	at android.speech.SpeechRecognizer.startListening(SpeechRecognizer.java:286)
	at com.csdcorp.speech_to_text.SpeechToTextPlugin.startListening$lambda-1(SpeechToTextPlugin.kt:286)
 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.lambda$yjNp_RCA9xqERSl0VjgCZu0NF-o(Unknown Source:0)
	at com.csdcorp.speech_to_text.-$$Lambda$SpeechToTextPlugin$yjNp_RCA9xqERSl0VjgCZu0NF-o.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
 	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by sowens-csd** [comment]
Does your manifest have all the required permissions in it as shown in the readme?

**Comment by altanod0627** [comment]
> Does your manifest have all the required permissions in it as shown in the readme?

Yes i have. That issue is only bixby service. I changed voice assistant app bixby to google voice. Then it.s work. Only samsung voice service cant use that

**Comment by sowens-csd** [comment]
Try the fix from this issue: https://github.com/csdcorp/speech_to_text/issues/153

**Comment by altanod0627** [comment]
> Try the fix from this issue: #153

Thanks for your comments, i fixed it that #153 following
