### ISSUE TITLE
Unexpected exception, Need android.permission.BLUETOOTH_CONNECT permission

### ISSUE THREAD

**Issue by naamapps** [csdcorp/speech_to_text#280]
Hey,
With latest version (5.4.0), when initializing the package, it throws an error and then the app immediately crashes on android (12 in my case).

```
E/flutter ( 6538): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(unknown, Unexpected exception, Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@67f601df: AdapterService getBondedDevices, null)
E/flutter ( 6538): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
E/flutter ( 6538): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
E/flutter ( 6538): <asynchronous suspension>
E/flutter ( 6538): #2      MethodChannelSpeechToText.initialize (package:speech_to_text_platform_interface/method_channel_speech_to_text.dart:39)
E/flutter ( 6538): <asynchronous suspension>
E/flutter ( 6538): #3      SpeechToText.initialize (package:speech_to_text/speech_to_text.dart:238)
```

Please help,
Thanks

**Comment by sowens-csd** [comment]
Sorry about that, I forgot to note a permission change in the docs. I'll put out 5.4.1 with a documentation change. The latest version supports bluetooth headsets for speech recognition. That requires new permissions in the manifest. Here's the new full permission list:

```xml
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT"/>
```

**Comment by sowens-csd** [comment]
Documentation updated, published as 5.4.1.

**Comment by naamapps** [comment]
Thanks, works great.

**Comment by rayrapetyan** [comment]
Somehow even after putting all new permissions above into AndroidManifest, I'm still getting:
```
E/AndroidRuntime(24941): Caused by: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@d04c5dd9: AdapterService getBondedDevices
```
on init.

This happens with SdkVersion 31 only.

As per https://issueexplorer.com/issue/stripe/stripe-terminal-android/171, client should explicitly request BLUETOOTH_CONNECT permission, which seems doesn't happen...
