### ISSUE TITLE
Google Glass Enterprise Edition not supported.

### ISSUE THREAD

**Issue by AlabasterAxe** [csdcorp/speech_to_text#364]
From this guide https://developers.google.com/glass-enterprise/guides/inputs-sensors#voice-recognition

> Note: Binding to the [SpeechRecognizer](https://developer.android.com/reference/android/speech/SpeechRecognizer) service isn't allowed, therefore the [SpeechRecognizer#startListening()](https://developer.android.com/reference/android/speech/SpeechRecognizer#startListening(android.content.Intent)) method won't work.

Not expecting a fix on this but I figured I'd file a bug anyway just as an FYI.

The stack trace looks like the following:

```
E/AndroidRuntime( 5013): java.lang.SecurityException: Not allowed to bind to service Intent { act=android.speech.RecognitionService cmp=com.google.android.libraries.assistant.soda.recognitionservice/.SodaRecognitionService }
E/AndroidRuntime( 5013): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1623)
E/AndroidRuntime( 5013): 	at android.app.ContextImpl.bindService(ContextImpl.java:1557)
E/AndroidRuntime( 5013): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:684)
E/AndroidRuntime( 5013): 	at android.speech.SpeechRecognizer.startListening(SpeechRecognizer.java:288)
E/AndroidRuntime( 5013): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.startListening$lambda-1(SpeechToTextPlugin.kt:304)
E/AndroidRuntime( 5013): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.$r8$lambda$yjNp_RCA9xqERSl0VjgCZu0NF-o(Unknown Source:0)
E/AndroidRuntime( 5013): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin$$ExternalSyntheticLambda3.run(Unknown Source:2)
E/AndroidRuntime( 5013): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime( 5013): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5013): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 5013): 	at android.app.ActivityThread.main(ActivityThread.java:6518)
E/AndroidRuntime( 5013): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5013): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime( 5013): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by AlabasterAxe** [comment]
Looks like https://github.com/csdcorp/speech_to_text/issues/336 is related.

**Comment by AlabasterAxe** [comment]
Okay I realize now glass implementation actually triggers a speech recognition UI which I'm assuming doesn't fit with the goal of this library. Will close this issue.

**Comment by sowens-csd** [comment]
I think that I should close the associated PR as well then?
